### ISSUE TITLE
[ViltordX] Modded items disappear

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [ErdbeerbaerLP/Better-Chesting#2]

**Comment by jgaines** [comment]
Yep, unusable as it stands right now.  I had a half dozen books from mods such as tinker's construct, environmental tech and some others.  Put in a chest, picked it up carried it around for a few minutes, set it down set down another, newly created and empty chest next to it (which might have been what caused the issue).  When I opened the combined chest I saw two generic minecraft books in it.

**Comment by ErdbeerbaerLP** [comment]
Update with the fix is now online!

https://minecraft.curseforge.com/projects/betterchesting/files/2722015
